# Generated by Django 5.2.9 on 2025-12-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='dealer_id',
            field=models.IntegerField(null=True, blank=True),
        ),
    ]

